// Generated by CoffeeScript 1.7.1
var bind, fn, fs, partial, read_file, read_rewrite, read_std, rewrite, write_file, write_std;

rewrite = require('./fella-rewrite-amd-source');

fs = require('fs');

fn = require('f-empower');

read_std = require('stdin');

bind = fn.bind, partial = fn.partial;

read_file = fs.readFile;

write_file = fs.writeFile;

write_std = bind(console.log, console);

read_rewrite = function(in_file_name, out_file_name, cb) {
  var on_read, read, write;
  read = in_file_name && (partial(read_file, in_file_name, {
    encoding: 'utf8'
  })) || read_std;
  write = out_file_name && (partial(write_file, out_file_name)) || write_std;
  on_read = function(err, str) {
    if (err) {
      cb(err);
    }
    return write(rewrite(str), cb);
  };
  return read(in_file_name, on_read);
};

module.exports = read_rewrite;
