// Generated by CoffeeScript 1.7.1
var amd_source, rewrite;

rewrite = require('./requeror-rewrite-amd-source');

amd_source = "define [\n  \"jquery\"\n  \"strang\"\n], (\n  $\n, fn\n) ->\n\n  { init } = fn";

console.log("\n>> STARTING\n");

console.log(rewrite(amd_source));
